name = "naroa-www-redirect"
main = "index.js"
compatibility_date = "2026-07-01"

# Intercepta ABSOLUTAMENTE TODO el tráfico de naroagutierrezgil.com (apex + subdominios) y redirige 301 a https://naroa.online/
routes = [
  { pattern = "*naroagutierrezgil.com/*", zone_name = "naroagutierrezgil.com" }
]
